2018-04-14 23:25:02,123 -Return -0
2018-04-14 23:25:02,124 -STDOUT -b''
2018-04-14 23:25:02,125 -STDERR -b''
2018-04-14 23:27:52,430 -Return -1
2018-04-14 23:27:52,431 -STDOUT -b''
2018-04-14 23:27:52,432 -STDERR -b'Traceback (most recent call last):\n  File "./00.py", line 53, in <module>\n    main()\n  File "./00.py", line 44, in main\n    v = artVoice(PIN)\nNameError: name \'artVoice\' is not defined\n'
